#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument
#+ Pings the IP 5 times
#+ if no argument pass displays a message

if [[ -n "$1"]]; then
   ping -c 5 "$1"
else
   echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
fi
